<?php

use Drupal\Component\Serialization\Json;

/**
 * @param $variables
 * Implements hook_preprocess_page()
 */
function curmodule_preprocess_page(&$variables){

    # Add library
    $variables['#attached']['library'][] =  'curmodule/canvasjs';
    $variables['#attached']['library'][] =  'curmodule/custom';
    //$variables['#attached']['drupalSettings']['curmodule']['custom']['currency_name'][] =  'USS';
}

/**
 * Implements hook_theme().
 */
function curmodule_theme() {

    return [
        'curmodule_template_firstpage' => [  // Назва теми
            'variables' => [ // Масив назви змінних
                'data' => NULL,
            ],
            'template' => 'first_curmodule_template', // Шлях до шаблону без .html.twig, в якому і будуть доступні змінні, що вказані вище
        ],
        'curmodule_template_pages' => [  // Назва теми
            'variables' => [ // Масив назви змінних
                'pages_name' => NULL,
                'data' => NULL,
            ],
            'template' => 'pages_curmodule_template', // Шлях до шаблону без .html.twig, в якому і будуть доступні змінні, що вказані вище
        ],
    ];
}

/**
 * Implements hook_cron().
 */
function curmodule_cron() {

//   // We access our configuration.
//   $cron_config = \Drupal::configFactory()->getEditable('curmodule.settings');

//   // Default to an hourly interval. Of course, cron has to be running at least hourly for this to work.
//   $interval = $cron_config->get('interval');
//   $interval = !empty($interval) ? $interval : 60;

//   // We usually don't want to act every time cron runs (which could be every minute) so keep a time for the next run in the site state.
//   $next_execution = \Drupal::state()->get('curmodule.next_execution');
//   $next_execution = !empty($next_execution) ? $next_execution : 0;

//   if (REQUEST_TIME >= $next_execution) {

//       // This is a silly example of a cron job.
//       // It just makes it obvious that the job has run without making any changes to your database.
//       \Drupal::logger('curmodule')->notice('CurModule - Крон запущено');
//       \Drupal::logger('curmodule')->notice('CurModule - $next_execution '.$next_execution);
//       if (\Drupal::state()->get('curmodule_show_status_message')) {
//           \Drupal::messenger()->addMessage(t('curmodule executed at %time', ['%time' => date_iso8601(REQUEST_TIME),]));
//           \Drupal::state()->set('curmodule_show_status_message', FALSE);
//       }
//       \Drupal::state()->set('curmodule.next_execution', REQUEST_TIME + $interval);
//   }
//

    //$uri = "https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange?json";


for ($x=35; $x<33; $x++) {
    $uri = "http://drupal8.ua/exchange".$x.".json";

    try {
        $response = \Drupal::httpClient()->get($uri, array('headers' => array('Accept' => 'application/json')));
        $currency_data = (string) $response->getBody();
        if (empty($currency_data)) {
            $currency_data = NULL;
        } else {
            $currency_data = Json::decode($currency_data);

            foreach ($currency_data as $currency) {
                // Шукаємо поточну валюту в таблиці nbu_table_info по її коду kod1
                // (результат false або kod1 якщо знайдено)
                $query = \Drupal::database()->select('nbu_table_info', 'info');
                $query->addField('info', 'kod1');
                $query->condition('kod1', $currency['r030']);
                $query_result = $query->execute()->fetchField();

                // Якщо дана валюта відсютня в таблиці, то добавляємо її в таблицю nbu_table_info
                if (!$query_result) {
                    $query = \Drupal::database()->insert('nbu_table_info');
                    $query->fields([
                        'kod1' => $currency['r030'],
                        'kod2' => $currency['cc'],
                        'name' => $currency['txt'],
                        'active' => 1,
                    ]);
                    $query->execute();
                }

                // Вставка обмінного курсу поточної валюти в таблицю nbu_table_data БД
                $query = \Drupal::database()->insert('nbu_table_data');
                $query->fields([
                    'id_inf' => $currency['r030'],
                    'exchange' => $currency['rate'],
                    'date' => $currency['exchangedate'],
                    //'date' => date("d.m.Y"),
                ]);
                $query->execute();
            }
        }
    }
    catch (Exception $e) {
        $currency_data = $e->getMessage();
    };
};


    // Вставка даних в таблицю nbu_table_data БД
    //$query = \Drupal::database()->insert('nbu_table_data');
    //$query->fields([
    //    'id_inf' => 0,
    //    'exchange' => $currency['r030'],
    //    'date' => date("d.m.Y"),
    //]);
    //$query->execute();

//    // Вставка даних в таблицю nbu_table_data БД
//    $query = \Drupal::database()->insert('nbu_table_data');
//    $query->fields([
//        'id_inf' => 0,
//        'exchange' => 22.444444,
//        'date' => date("d.m.Y"),
//    ]);
//    $query->execute();

}